[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32-gcc"
rustflags = ["-C", "target-feature=+crt-static"] # Exemplo, caso precise linkar as bibliotecas C estaticamente
[target.x86_64-pc-windows-gnu.release]
linker = "x86_64-w64-mingw32-gcc"